### ISSUE TITLE
Atom: Failed to find plugin phaser

### ISSUE THREAD

**Issue by k3muri84** [angelozerr/tern-phaser#13]
Running on OSX and as described here https://github.com/angelozerr/tern-phaser/wiki/UseTernPhaserWithAtom
i installed tern-phaser via npm install -g tern-phaser.
It was installed to /usr/local/lib/node_modules/tern-phaser.
Atom still can't find it.
How is the lookup solved? Can i fix the path?

**Comment by angelozerr** [comment]
@echorebel I don't know Atom. I have contacted the guy who has written https://github.com/angelozerr/tern-phaser/wiki/UseTernPhaserWithAtom

In the doc, there were an error. Your .tern-project lokks like this:

``` json
{
  "ecmaVersion": 5,
  "libs": ["browser"],
  "plugins": {
    "phaser": {}
  }
}
```

(you must add ':' after "phaser")

Perhaps it's your problem?

Otherwise I suggest you that you post your question at https://github.com/tststs/atom-ternjs/issues

**Comment by k3muri84** [comment]
thx for the info, yep i know there was an error, but didn't made that mistake.
will post the question over there.

**Comment by NathanLovato** [comment]
Sorry, I don't have a mac here to help you. You can always install any package manually, dunno the command to navigate folders on mac though (but I heard the command prompt is better than on windows). Asking directly to mac atom users would probably be best yep - simply ask where modules should go to be available globally? Sorry for that!
